# Generated by Django 3.1.7 on 2021-04-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_dt', models.DateTimeField(auto_now=True)),
                ('cars_brand', models.CharField(max_length=20, verbose_name='Марка')),
                ('cars_model', models.CharField(max_length=20, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
